// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	service "github.com/mikhailbolshakov/cryptocare/src/service"
)

// BidGenerator is an autogenerated mock type for the BidGenerator type
type BidGenerator struct {
	mock.Mock
}

// Init provides a mock function with given fields: cfg
func (_m *BidGenerator) Init(cfg *service.Config) {
	_m.Called(cfg)
}

// Run provides a mock function with given fields: ctx
func (_m *BidGenerator) Run(ctx context.Context) {
	_m.Called(ctx)
}

// Stop provides a mock function with given fields: ctx
func (_m *BidGenerator) Stop(ctx context.Context) {
	_m.Called(ctx)
}

type mockConstructorTestingTNewBidGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewBidGenerator creates a new instance of BidGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBidGenerator(t mockConstructorTestingTNewBidGenerator) *BidGenerator {
	mock := &BidGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
