// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// CreateSubscription provides a mock function with given fields: _a0, _a1
func (_m *Controller) CreateSubscription(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// DeleteSubscription provides a mock function with given fields: _a0, _a1
func (_m *Controller) DeleteSubscription(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GetProfitableChainDetails provides a mock function with given fields: _a0, _a1
func (_m *Controller) GetProfitableChainDetails(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GetProfitableChains provides a mock function with given fields: _a0, _a1
func (_m *Controller) GetProfitableChains(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GetSubscription provides a mock function with given fields: _a0, _a1
func (_m *Controller) GetSubscription(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// GetUserSubscriptions provides a mock function with given fields: _a0, _a1
func (_m *Controller) GetUserSubscriptions(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *Controller) Login(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Logout provides a mock function with given fields: _a0, _a1
func (_m *Controller) Logout(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// PutBid provides a mock function with given fields: _a0, _a1
func (_m *Controller) PutBid(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Ready provides a mock function with given fields: _a0, _a1
func (_m *Controller) Ready(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// Registration provides a mock function with given fields: _a0, _a1
func (_m *Controller) Registration(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// SetPassword provides a mock function with given fields: _a0, _a1
func (_m *Controller) SetPassword(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// TokenRefresh provides a mock function with given fields: _a0, _a1
func (_m *Controller) TokenRefresh(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

// UpdateSubscription provides a mock function with given fields: _a0, _a1
func (_m *Controller) UpdateSubscription(_a0 http.ResponseWriter, _a1 *http.Request) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewController interface {
	mock.TestingT
	Cleanup(func())
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewController(t mockConstructorTestingTNewController) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
